{% set name = "oci-cli" %}
{% set version = "3.54.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bfeb12dcc4ae361fc0bfdf867c0584c72b0e6c0eec8a7663ac46774fe63378fa
  # https://github.com/oracle/oci-cli

build:
  entry_points:
    - oci=oci_cli.cli:cli
    - create_backup_from_onprem=oci_cli.scripts.database.dbaas:create_backup_from_onprem
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >70.0.0
  # https://github.com/oracle/oci-cli/blob/master/setup.py
  run:
    - python >={{ python_min }}
    - oci ==2.149.2
    - arrow >=1.0.0
    - certifi ==2025.1.31
    - click ==8.0.4
    - cryptography >=3.2.1,<46.0.0
    - jmespath ==0.10.0
    - python-dateutil >=2.5.3,<3.0.0
    - pytz >=2016.10
    - six >=1.15.0
    - terminaltables ==3.1.10
    - pyopenssl >=17.5.0,<25.0.0
    - pyyaml >=5.4,<=6.0.1
    - prompt-toolkit >=3.0.38,<=3.0.43

test:
  imports:
    - alloy
    - common_util
    - interactive
    - oci_cli
    - services
  commands:
    - pip check
    - oci --help
    # Requires cx_Oracle, not needed for Oracle Cloud
    # - create_backup_from_onprem --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oracle/oci-cli
  summary: Oracle Cloud Infrastructure CLI
  license: Apache-2.0 AND UPL-1.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - manics
