github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
bot:
  inspection: update-grayskull
  # Tightly coupled to oci version
  check_solvable: true
  automerge: true
